version: "3.8"

services:
  kitchen-api:
    build: .
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      PORT: 3002
      DATABASE_URL: ${DATABASE_URL}
      ORDER_API_URL: ${ORDER_API_URL}
      DELIVERY_API_URL: ${DELIVERY_API_URL}
      NOTIFICATION_API_URL: ${NOTIFICATION_API_URL}
    networks:
      - shoong-network

networks:
  shoong-network:
    external: true